//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardLibros.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadResponsable
    {
        public EntidadResponsable()
        {
            this.Comprobante = new HashSet<Comprobante>();
            this.Movimiento = new HashSet<Movimiento>();
        }
    
        public int IdEntidadResponsable { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> IdTipoEntidad { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public Nullable<decimal> Detraccion { get; set; }
        public string Tipo { get; set; }
        public int IdEmpresa { get; set; }
        public string NroDocumento { get; set; }
    
        public virtual ICollection<Comprobante> Comprobante { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoEntidad TipoEntidad { get; set; }
        public virtual ICollection<Movimiento> Movimiento { get; set; }
    }
}
