//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardLibros.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public Moneda()
        {
            this.CuentaBancaria = new HashSet<CuentaBancaria>();
            this.Comprobante = new HashSet<Comprobante>();
        }
    
        public int IdMoneda { get; set; }
        public string Nombre { get; set; }
        public string Simbolo { get; set; }
    
        public virtual ICollection<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual ICollection<Comprobante> Comprobante { get; set; }
    }
}
