//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullardLibros.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public int IdTipoCambio { get; set; }
        public int IdMoneda { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
    
        public virtual Moneda Moneda { get; set; }
    }
}
